"""panchayat_update

Revision ID: 80949ea83f0e
Revises: 8f94e7ad20fd
Create Date: 2025-03-06 16:00:11.202745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80949ea83f0e'
down_revision = '8f94e7ad20fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_crops', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'crops', ['crop_id'], ['id'])
        batch_op.create_foreign_key(None, 'block_territory', ['bt_id'], ['id'])

    with op.batch_alter_table('block_groundwater', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'block_territory', ['bt_id'], ['id'])

    with op.batch_alter_table('block_industries', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'industries', ['industry_id'], ['id'])
        batch_op.create_foreign_key(None, 'block_territory', ['bt_id'], ['id'])

    with op.batch_alter_table('block_livestocks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'block_territory', ['bt_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'livestocks', ['livestock_id'], ['id'])

    with op.batch_alter_table('block_lulc', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'lulc', ['lulc_id'], ['id'])
        batch_op.create_foreign_key(None, 'block_territory', ['bt_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('block_pops', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'population', ['population_id'], ['id'])
        batch_op.create_foreign_key(None, 'block_territory', ['bt_id'], ['id'])

    with op.batch_alter_table('block_progress', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'block_category', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'block_territory', ['bt_id'], ['id'])

    with op.batch_alter_table('block_rainfall', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'block_territory', ['bt_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('block_territory', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'blocks', ['block_id'], ['id'])
        batch_op.create_foreign_key(None, 'districts', ['district_id'], ['id'])
        batch_op.create_foreign_key(None, 'panchayats', ['panchayat_id'], ['id'])
        batch_op.create_foreign_key(None, 'states', ['state_id'], ['id'])

    with op.batch_alter_table('block_water_transfers', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'block_territory', ['bt_id'], ['id'])
        batch_op.create_foreign_key(None, 'block_transfer_types', ['transfer_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'block_transfer_sectors', ['transfer_sector_id'], ['id'])

    with op.batch_alter_table('block_waterbodies', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'block_territory', ['bt_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'waterbody_types', ['wb_type_id'], ['id'])

    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'districts', ['district_lgd_code'], ['lgd_code'])

    with op.batch_alter_table('crop_census', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'territory_joins', ['territory_id'], ['id'])
        batch_op.create_foreign_key(None, 'panchayats', ['panchayat_lgd_code'], ['lgd_code'])
        batch_op.create_foreign_key(None, 'crops', ['crop_id'], ['id'])

    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'states', ['state_lgd_code'], ['lgd_code'])

    with op.batch_alter_table('groundwater_extractions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'panchayats', ['panchayat_id'], ['id'])
        batch_op.create_foreign_key(None, 'blocks', ['block_id'], ['id'])
        batch_op.create_foreign_key(None, 'territory_joins', ['tj_id'], ['id'])
        batch_op.create_foreign_key(None, 'districts', ['district_id'], ['id'])

    with op.batch_alter_table('livestock_census', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'territory_joins', ['tj_id'], ['id'])
        batch_op.create_foreign_key(None, 'livestocks', ['livestock_id'], ['id'])

    with op.batch_alter_table('lulc_census', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'lulc', ['lulc_id'], ['id'])
        batch_op.create_foreign_key(None, 'territory_joins', ['tj_id'], ['id'])

    with op.batch_alter_table('panchayats', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'states', ['state_lgd_code'], ['lgd_code'])
        batch_op.create_foreign_key(None, 'districts', ['district_lgd_code'], ['lgd_code'])
        batch_op.create_foreign_key(None, 'blocks', ['block_lgd_code'], ['lgd_code'])

    with op.batch_alter_table('population_census', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'population', ['population_id'], ['id'])
        batch_op.create_foreign_key(None, 'territory_joins', ['territory_id'], ['id'])

    with op.batch_alter_table('rainfall_data', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'districts', ['district_id'], ['id'])

    with op.batch_alter_table('territory_joins', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'panchayats', ['panchayat_id'], ['id'])
        batch_op.create_foreign_key(None, 'districts', ['district_id'], ['id'])
        batch_op.create_foreign_key(None, 'blocks', ['block_id'], ['id'])
        batch_op.create_foreign_key(None, 'states', ['state_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'blocks', ['block_id'], ['id'])
        batch_op.create_foreign_key(None, 'districts', ['district_id'], ['id'])
        batch_op.create_foreign_key(None, 'panchayats', ['panchayat_id'], ['id'])

    with op.batch_alter_table('villages', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'states', ['state_lgd_code'], ['lgd_code'])
        batch_op.create_foreign_key(None, 'districts', ['district_lgd_code'], ['lgd_code'])
        batch_op.create_foreign_key(None, 'panchayats', ['panchayat_lgd_code'], ['lgd_code'])
        batch_op.create_foreign_key(None, 'blocks', ['block_lgd_code'], ['lgd_code'])

    with op.batch_alter_table('waterbodies_census', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'districts', ['district_code'], ['lgd_code'])
        batch_op.create_foreign_key(None, 'territory_joins', ['tj_id'], ['id'])
        batch_op.create_foreign_key(None, 'waterbody_types', ['waterbody_id'], ['id'])
        batch_op.drop_column('panchayat_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waterbodies_census', schema=None) as batch_op:
        batch_op.add_column(sa.Column('panchayat_code', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('villages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('territory_joins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('rainfall_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('population_census', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('panchayats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('lulc_census', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('livestock_census', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('groundwater_extractions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('crop_census', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('block_waterbodies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('block_water_transfers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('block_territory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('block_rainfall', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('block_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('block_pops', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('block_lulc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('block_livestocks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('block_industries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('block_groundwater', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('block_crops', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
