"""added ticket

Revision ID: cf1a0d77d7c7
Revises: 8f94e7ad20fd
Create Date: 2025-03-24 22:39:04.924573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1a0d77d7c7'
down_revision = '8f94e7ad20fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Open', 'In Progress', 'Resolved', 'Closed', name='ticket_status'), nullable=True),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'High', 'Critical', name='ticket_priority'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('o_groundwater_extractions')
    with op.batch_alter_table('groundwater_extractions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'blocks', ['block_id'], ['id'])
        batch_op.create_foreign_key(None, 'panchayats', ['panchayat_id'], ['id'])
        batch_op.create_foreign_key(None, 'districts', ['district_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groundwater_extractions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('o_groundwater_extractions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stage_of_extraction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rainfall', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recharge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('discharge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('extractable', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('extraction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('village_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('block_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tj_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], name='groundwater_extractions_block_id_fkey'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name='groundwater_extractions_district_id_fkey'),
    sa.ForeignKeyConstraint(['tj_id'], ['territory_joins.id'], name='groundwater_extractions_tj_id_fkey'),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], name='groundwater_extractions_village_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='groundwater_extractions_pkey')
    )
    op.drop_table('tickets')
    # ### end Alembic commands ###
