"""panchyat_array_added

Revision ID: fbc0c73c9faf
Revises: 80949ea83f0e
Create Date: 2025-03-06 19:13:10.125301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fbc0c73c9faf'
down_revision = '80949ea83f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('panchyat_id', postgresql.ARRAY(sa.Integer()), nullable=True))
        batch_op.drop_constraint('users_panchayat_id_fkey', type_='foreignkey')
        batch_op.drop_column('panchayat_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('panchayat_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('users_panchayat_id_fkey', 'panchayats', ['panchayat_id'], ['id'])
        batch_op.drop_column('panchyat_id')

    # ### end Alembic commands ###
